//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroMapNavigation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetroMapNavigation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kiev_metro {
            get {
                object obj = ResourceManager.GetObject("kiev_metro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,132 0,492 Академмістечко R
        ///0,172 0,492 Житомирська R
        ///0,212 0,492 Святошин R
        ///0,252 0,492 Нивки R
        ///0,292 0,492 Берестейська R
        ///0,332 0,492 Шулявська R
        ///0,377 0,492 ПолітехническийІнститут R
        ///0,425 0,492 Вокзальна R
        ///0,464 0,492 Університет R
        ///0,532 0,455 Театральна R
        ///0,603 0,42 Хрещатик R
        ///0,675 0,42 Арсенальна R
        ///0,731 0,42 Дніпро R
        ///0,772 0,36 Гідропарк R
        ///0,795 0,324 Лівобережна R
        ///0,819 0,287 Дарниця R
        ///0,851 0,24 Чернігівська R
        ///0,891 0,18 Лісова R
        ///0,348 0,18 Сирець G
        ///0,38 0,228 Дорогожичі G
        ///0,4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProjectPoints {
            get {
                return ResourceManager.GetString("ProjectPoints", resourceCulture);
            }
        }
    }
}
